name: code_data
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.0 # Adicionando provider
  sqflite: ^2.0.0  # Adicionando sqflite para persistência de dados
  path: ^1.8.0    # Adicionando path para gerenciar caminhos

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
